### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by adhamox** [sapienza/CodeIgniter-admin-panel#1]
Just by following the instructions and installing, I get 
![screen shot 2013-05-25 at 10 17 33 am](https://f.cloud.github.com/assets/953676/563797/945e60e0-c513-11e2-87d4-dfd516c0147a.png)

**Comment by sapienza** [comment]
This version is outdated, i'm fixing and updating a few things.
i'll push new files this week, sorry about that!

**Comment by sapienza** [comment]
@adhamox i updated the project, can you please download / clone the files, and try it again? thanks for trying out this project!
