### ISSUE TITLE
The username and password you have supplied in your MD is incorrect

### ISSUE THREAD

**Issue by bielefeldt** [sapienza/CodeIgniter-admin-panel#2]
![screen shot 2013-05-30 at 4 15 52 pm](https://f.cloud.github.com/assets/1554907/587422/c57238ae-c965-11e2-8b27-b46978cac672.png)

**Comment by sapienza** [comment]
The version was outdated, and the live preview is no longer available in the old url, can you please download / clone the files again, and try it again? Thanks!
