### ISSUE TITLE
Undefined variable: filter_session_data

### ISSUE THREAD

**Issue by sreekanthgoud** [sapienza/CodeIgniter-admin-panel#3]
hi, 
when i am using admin manufacturers index page pagination(second ,third pages) accessing getting below error..

Message: Undefined variable: filter_session_data

Filename: controllers/admin_manufacturers.php

Line Number: 102

and when i am use as prodcut page..not getting error..
if you have know error  please share me..

Thank you

**Comment by sapienza** [comment]
Hi, thanks for trying out the project! the files were updated, can you please download/clone the files again?

**Comment by sreekanthgoud** [comment]
i have downloaded and tested...not working admin manufacturers index page pagination error.

**Comment by sapienza** [comment]
Same error as before?

**Comment by sreekanthgoud** [comment]
yes..same error

**Comment by sapienza** [comment]
@sreekanthgoud  simple verification was missing =)

fixed in the las commit, see the code!
https://github.com/sapienza/CodeIgniter-admin-panel/commit/d69ed86092cd524b8a62a7c68e00da8b8210c8e6

**Comment by sreekanthgoud** [comment]
thank you

**Comment by sapienza** [comment]
you're welcome! feel free to fork the repository, and star it as well ^_^
